import { Inter } from "next/font/google";
import "app/globals.css";
import Sidebar from "./components/Sidebar/Sidebar";
import RightSidebar from "./components/RightSidebar/RightSidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, searchParams }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container">
          <Sidebar></Sidebar>

          {children}

          <RightSidebar params={searchParams}></RightSidebar>
        </div>
      </body>
    </html>
  );
}
